# Generated by Django 5.0.2 on 2024-08-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_category_alter_job_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
