# Generated by Django 5.0.2 on 2024-08-18 04:18

import jobs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_contact',
            field=jobs.models.EmailOrURLField(blank=True, max_length=200, null=True),
        ),
    ]
