# Generated by Django 5.0.2 on 2024-08-18 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_application_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now, max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
