# Generated by Django 5.0.2 on 2024-07-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('created_at', '-job_count', '-updated_at', 'name'), 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
