# Generated by Django 5.0.2 on 2024-07-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('created_at', '-job_count', '-name'), 'verbose_name_plural': 'Locations'},
        ),
    ]
